#!/bin/sh

# update psnames and sort order, which also normalizes it
echo "-----Normalizing UFO..."
echo "-----Updating production names..."
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/DoulosSIL-Regular.ufo -x

echo "-----Updating glyph orders..."
psfsetglyphorder --header sort_final_cdg -i source/glyph_data.csv source/DoulosSIL-Regular.ufo -x

echo "-----Preflight completed!"
