#!/bin/sh

echo "-----Updating UFOs from Glyphs file..."
psfglyphs2ufo --nofea source/DoulosSILRoman.glyphs source

# update psnames and sort order, which also normalizes it
echo "-----Normalizing UFO..."
echo "-----Updating production names..."
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/DoulosSIL-Regular.ufo -x

echo "-----Updating glyph orders..."
psfsetglyphorder --header sort_final_cdg -i source/glyph_data.csv source/DoulosSIL-Regular.ufo -x

echo "-----Rebuilding composites..."
psfbuildcomp -i source/composites.txt -c -n source/DoulosSIL-Regular.ufo -p backup=False

echo "-----Updating woff metadata file..."
psfmakewoffmetadata -q -n "DoulosSIL" -i "org.sil.fonts" source/DoulosSIL-Regular.ufo

echo "-----Preflight completed!"
